### ISSUE TITLE
There is no  dir 'projects/DDETRS/ddetrs/models/ops/'

### ISSUE THREAD

**Issue by NingYuanxiang** [wjf5203/VNext#1]
Thanks for your excellent work.

**Comment by wjf5203** [comment]
Sorry for this mistake, I have updated the INSTALL.md and you can check it now. :)

**Comment by NingYuanxiang** [comment]
thanks

**Comment by NingYuanxiang** [comment]
您好，我是中国农业大学的研究生，目前即将研二，我目前方向是视频实例分割，看了您的非常nice的工作。想要认识你一下。方便加个微信吗？  ps:(Zephryos-N-113)
