### ISSUE TITLE
Can you provide a training log of one IDOL model?

### ISSUE THREAD

**Issue by Cynthiacoding** [wjf5203/VNext#10]
Hi，IDOL is an excellent paper, with many wonderful designs.
Unfortunately, due to resource constraints, I can't fully train it. 
Can you provide a training log of one IDOL model on the Youtube-VIS dataset? 
Thanks.

**Comment by wjf5203** [comment]
Hi, thanks for your attention~
Here is a training log for ResNet-50 backbone on YTVIS2019 with 8*A100. Hope it helps~
https://drive.google.com/file/d/16jqwbEzSkY-qcVZYYJeZ2vj8-Mffm30T/view?usp=sharing
