### ISSUE TITLE
the definition of proposed model 

### ISSUE THREAD

**Issue by RaymondWang987** [wjf5203/VNext#17]
Thanks for releasing the code. Where can we find the pytorch model definition of IDOL? The IDOL is now presented by config file and Vnext library. I cannot find pytorch model definition code of IDOL.

**Comment by wjf5203** [comment]
Thanks for your attention.
For definition of IDOL, please refer to https://github.com/wjf5203/VNext/blob/main/projects/IDOL/idol/idol.py
and https://github.com/wjf5203/VNext/tree/main/projects/IDOL/idol/models

**Comment by RaymondWang987** [comment]
Thanks for your reply!
