### ISSUE TITLE
about SeqFormer/train_net.py 

### ISSUE THREAD

**Issue by lywang76** [wjf5203/VNext#20]
When i used your train_net.py for seqformer, they report errors for:

from detectron2.projects.seqformer import add_seqformer_config, build_detection_train_loader, build_detection_test_loader
from detectron2.projects.seqformer.data import (
  YTVISDatasetMapper, YTVISEvaluator, get_detection_dataset_dicts,DetrDatasetMapper,)

I think the import path may not be correct.

**Comment by wjf5203** [comment]
All training commands should be executed in the root directory VNext/ , please check this.
