### ISSUE TITLE
SeqFormer question

### ISSUE THREAD

**Issue by lywang76** [wjf5203/VNext#22]
In configuration.py

 cfg.INPUT.SAMPLING_FRAME_NUM = 1

Does it mean that only one frame in the videos is selected as input?

**Comment by wjf5203** [comment]
Yes, SAMPLING_FRAME_NUM is the number of selected frames per video. For IDOL, SAMPLING_FRAME_NUM should be set to 2, the first is key frame and the second is reference frame.
