### ISSUE TITLE
gpu util = 0 while running inference

### ISSUE THREAD

**Issue by shulou1996** [wjf5203/VNext#26]
Hello, appreciate for your great job!

There is a problem when I run your inference script on ytvis dataset
`python3 projects/IDOL/train_net.py --config-file projects/IDOL/configs/XXX.yaml --num-gpus 8 --eval-only MODEL.WEIGHTS /path to my .pth`

Everything works well and GPU memory looks normal, but GPU util is always 0.
![image](https://user-images.githubusercontent.com/105587339/188592343-e0a0c3a6-0a14-496f-9092-69aca01844e7.png)

Total infer time is around 2h, I don't know if all gpus are correctly used during inference.

**Comment by wjf5203** [comment]
Hi, thanks for your attention~
Typically, inference on YTVIS only takes a few minutes. Two hours is an abnormal time, so maybe you can check whether the cpu utilization is too high during inference.
If yes, you can set cfg.MODEL.IDOL.MERGE_ON_CPU=True in config file, which will avoid processing data on cpu and speed up inference.

**Comment by shulou1996** [comment]
Yes, the default is True and setting it to False can significantly speed up.
Thanks.
