### ISSUE TITLE
Use so much memory during inference

### ISSUE THREAD

**Issue by f414158949** [wjf5203/VNext#27]
when I try to inference a long video dataset (about 200 frames per video) on a hardware with 256G memory, 
i meet the error and get crash:
`DefaultCPUAllocator: can't allocate memory: you tried to allocate 522746265600 bytes. Error code 12 (Cannot allocate memory)`

is there a way to generate the result json file with a smaller memory?

**Comment by wjf5203** [comment]
Hi, thanks for your attention.

The reason for this is that OVIS videos are too long, for convenience, when the object disappears, we added zero masks to the corresponding frame to maintain the integrity of the mask sequence. This causes a lot of wasted memory.

We have fixed this bug and the code can now perform inference on OVIS on a machine within 200G memory.
