### ISSUE TITLE
Evaluate Module

### ISSUE THREAD

**Issue by lirui-9527** [wjf5203/VNext#28]
Hi,Dr.Wu,thanks for your amazing work and open-source code！But when I inferedthe model, I didn't find the evaluation function code in the ytvis_eval.py. Could you please provide the evaluation function code for inferring?

**Comment by wjf5203** [comment]
Hi, thanks for your attention.
Since the annotations of valid set are no released, you need to manually submit the results.json to the server to verify the results after the inference.
Sever links: https://youtube-vos.org/dataset/vis/

**Comment by lirui-9527** [comment]
OK, thank you for your reply!
