### ISSUE TITLE
Why Detectron2 and not MMdet (OpenMMLab projects .etc)?

### ISSUE THREAD

**Issue by yingkaining** [wjf5203/VNext#4]
首先非常感谢大佬提供这么一个仓库，我相信一定会对未来的VIS研究带来很大的便利以及统一的比较框架。但是，为什么采用detectron2，而不使用更加健全好用的openmmlab的仓库呢，这两个仓库都用过，detectron2使用起来比较晦涩，远不如mmdet，而且我本人也有想写一个基于mmdet的算法库。

**Comment by iFighting** [comment]
> 首先非常感谢大佬提供这么一个仓库，我相信一定会对未来的VIS研究带来很大的便利以及统一的比较框架。但是，为什么采用detectron2，而不使用更加健全好用的openmmlab的仓库呢，这两个仓库都用过，detectron2使用起来比较晦涩，远不如mmdet，而且我本人也有想写一个基于mmdet的算法库。

@yingkaining thanks for your advice!
1. We hope that this repo can help all the video recognition task instead of only the VIS task.
2. We are more familiar with detectron2 framework, you can also translate this repo to mmdet. welcome to do this
