### ISSUE TITLE
请问ECCV2022比赛的训练集是什么？

### ISSUE THREAD

**Issue by yingkaining** [wjf5203/VNext#5]
如题，请问训练集是和2021一样的吗，我看codalab没有提供训练集

**Comment by iFighting** [comment]
> 如题，请问训练集是和2021一样的吗，我看codalab没有提供训练集

@yingkaining i will check this and reply to you

**Comment by yingkaining** [comment]
many thanks :)

**Comment by iFighting** [comment]
> 如题，请问训练集是和2021一样的吗，我看codalab没有提供训练集

which dataset do you use? YouTube VIS or OVIS?

**Comment by iFighting** [comment]
> > 如题，请问训练集是和2021一样的吗，我看codalab没有提供训练集
> 
> which dataset do you use? YouTube VIS or OVIS?

i have confirmed， it is the same

**Comment by yingkaining** [comment]
I use the youtubeVIS, thanks!

**Comment by iFighting** [comment]
> I use the youtubeVIS, thanks!

welcome to our  ECCV 2022 Workshop(Multiple Object Tracking and Segmentation in Complex Environments)
the website is https://motcomplex.github.io

**Comment by yingkaining** [comment]
can we use extra training data in VIS track?
