### ISSUE TITLE
OVIS inference video sequence too long ??

### ISSUE THREAD

**Issue by CarlHuangNuc** [wjf5203/VNext#6]
Hi,
     i try reproduce paper about OVIS performance.
But i also get crash when run inference about OVIS.. 

     May be sequence too long ???  about 200 frames..

**Comment by wjf5203** [comment]
Thanks for your attention.
In our experiments, Inference on OVIS needs 32G GPU memory, and you need to set cfg.MODEL.IDOL.MERGE_ON_CPU = True. Maybe you should check this.
We will update the model zoo on OVIS and configs soon~

**Comment by CarlHuangNuc** [comment]
thanks

**Comment by CarlHuangNuc** [comment]
Hi，
If we open Merge_on_CPU,  what size CPU memory our model need in inference phrase ?
I just  try 256G Memory,, can not work..

**Comment by wjf5203** [comment]
Thanks for raising this issue. As the video gets longer, our post-processing of the segmentation results may waste some memory, which is not noticeable on YTVIS. We will fix this this week.

**Comment by CarlHuangNuc** [comment]
fixed it
