### ISSUE TITLE
i try infer video output keyerror

### ISSUE THREAD

**Issue by wuhongsheng** [wjf5203/VNext#7]
![image](https://user-images.githubusercontent.com/10295461/182057665-925e7c40-1d9d-46b4-b61e-c0806dc42ae2.png)

**Comment by wjf5203** [comment]
Thanks for your attention~

**Comment by wjf5203** [comment]
Thanks for your attention~
The code of the demo is not ready, and video demo is supported yet. We will update this part of the code and usage in the near future.

**Comment by CarlHuangNuc** [comment]
> Thanks for your attention~ The code of the demo is not ready, and video demo is supported yet. We will update this part of the code and usage in the near future.

Where i can find the video demo code ?
