### ISSUE TITLE
Why OVIS need so many Memory??

### ISSUE THREAD

**Issue by CarlHuangNuc** [wjf5203/VNext#8]
I try to inference on a hardware with 512G memory,  some video preprocess waste all memory and crask .

When I change input size from 720 --> 100, can run sucessfully.

**Comment by wjf5203** [comment]
Thanks for raising this issue. As the video gets longer, our post-processing of the segmentation results may waste some memory, which is not noticeable on YTVIS. We will fix this this week.

**Comment by CarlHuangNuc** [comment]
Fixed it
