### ISSUE TITLE
RuntimeError: Timed out waiting 1800000ms for send operation to complete

### ISSUE THREAD

**Issue by ywwwei** [wjf5203/VNext#9]
Hi! Thanks for the excellent work.

I got the Error when running IDOL with multi-processes on a single node
```
python projects/IDOL/train_net.py --config-file projects/IDOL/configs/ytvis19_r50.yaml --num-gpus 8
```
Error：
```
RuntimeError: [/opt/conda/conda-bld/pytorch_1656352430114/work/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete
```
The program is stuck on some iteration and one of the 8 GPUs is idle and its util is 0.

Do you know what is going on? and how to fix it?

Thanks!

**Comment by wjf5203** [comment]
Hi, thanks for your attention.
I don't have this issue on my side.
Does this error appear every time? Have you tried reducing the batchsize？
Do you meet out of memory problem? Please provide more details.

**Comment by wangjk666** [comment]
@ywwwei I met the same problem with you, I wonder whether you have solved it? Thx
